[package]
name = "rust_scorer"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
pyo3 = { version = "0.27.1", features = ["extension-module"] }

[build-dependencies]
pyo3-build-config = "0.27.1"

[lib]
name = "rust_scorer"
crate-type = ["cdylib"]
